name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    env-test:
      runs-on: self-hosted
      steps:
        - name: Debug Docker permissions
          run: |
            echo "=== User ==="
            whoami
            echo "=== ID ==="
            id
            echo "=== Groups ==="
            groups
            echo "=== Docker socket ==="
            ls -l /var/run/docker.sock
            echo "=== Docker version ==="
            docker version   
    full-test:
        container: cuaesd/aesd-autotest:24-assignment7-buildroot
        runs-on: self-hosted
        timeout-minutes: 720
        steps:       
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
